### ISSUE TITLE
'PosixPath' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by dakoller** [rgs258/django-markdown-view#12]
Under Django 3.2.12 and python 3.8 I get in the default configration "AttributeError at /impressum/
'PosixPath' object has no attribute 'endswith'".

Request Method: | GET
-- | --
http://localhost:8000/impressum/
3.2.12
AttributeError
'PosixPath' object has no attribute 'endswith'
/usr/local/lib/python3.8/site-packages/markdown_view/loaders.py, line 49, in get_template_sources
/usr/local/bin/python
3.8.12
['/code',  '/code',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/usr/local/lib/python3.8/site-packages']
Sat, 05 Mar 2022 21:47:08 +0000

**Comment by carltongibson** [comment]
This is the move to `Path` objects. Looks like #11 have a fix for this.

**Comment by FlipperPA** [comment]
This has been fixed by #11 - thank folks!
