### ISSUE TITLE
Unable to follow "usage" in readme

### ISSUE THREAD

**Issue by mattmakai** [rgs258/django-markdown-view#2]
Hey @rgs258 thanks for open sourcing this code. I'm actually unable to follow the usage instructions. It appears that in `markdown_view/constants.py` there is an import statement `from markdown_view.markdown_extensions import ImageExtension`, but `markdown_extensions` is not included with the code and therefore causes an error. This prevents the extension from working as specified in the README.

**Comment by rgs258** [comment]
@mattmakai thank you for this feedback! I'll have a look tomorrow and get this corrected. I really appreciate your feedback!

**Comment by rgs258** [comment]
It looks like I somehow failed to commit the file. I've done so in #4 

I need to make tests for this repo, but I don't have time at the moment. One day, the tests will catch my dumb mistakes

**Comment by mattmakai** [comment]
thanks @rgs258, it happens to the best of us! I'll give it a test shortly. assuming everything works great, you'll likely want to update the [PyPI package](https://djangopackages.org/packages/p/django-markdown-view/) as well
