### ISSUE TITLE
Unable to import MarkdownView or anything in views.py in version 0.0.2

### ISSUE THREAD

**Issue by mattmakai** [rgs258/django-markdown-view#5]
Hey @rgs258, sorry to bring this up again but in 0.0.2 the same problem is still there. It's not possible to follow the Usage section under README because `views` is not available. Here's what happens when I import the package:

```
>>> import markdown_view
>>> dir(markdown_view)
['ImproperlyConfigured', 'SETTINGS_TYPES', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'apps', 'checks', 'default_app_config', 'instance_type', 'models', 'settings', 'variable']
```

No `views` module available in the list and it immediately throws `ImportError: cannot import name 'MarkdownView' from 'markdown_view' (/Users/matt/Envs/djmdview/lib/python3.8/site-packages/markdown_view/__init__.py)` when you try to import one of the three views in the usage instructions.

I recommend doing a completely fresh virtualenv then installing django and django-markdown-view then you should be able to immediately reproduce this error.

**Comment by rgs258** [comment]
@mattmakai great catch! I'm so sorry for the confusion! I refactored the views into views.py but had failed to update the README.md with `from markdown_view.views import StaffMarkdownView`, emphasis on `.views`. I'll make that change now!

**Comment by mattmakai** [comment]
awesome, that worked for me @rgs258. is there a flag to prevent the the "table of contents" from being part of what's rendered? or is the best bet just to hide that with some CSS? it would be useful if that `<section>` element for the table of contents had an id so it would be easier to grab in CSS or JS

**Comment by rgs258** [comment]
Hey Matt,

The fastest way to get rid of the TOC is to create a new template for
rendering the page, and don’t include the TOC. Put the template anywhere
your template engine will load time it, and set the
DEFAULT_MARKDOWN_VIEW_TEMPLATE
setting to the path/name of the template.

In a future version, maybe TOC will just be optional. I’ll also add an id
to the section like you suggest.

Thanks

**Comment by mattmakai** [comment]
This is awesome context, thank you so much for your quick responses and help @rgs258! awesome work here on this project. definitely a need for a lightweight way to render Markdown in Django projects

**Comment by rgs258** [comment]
Closing this. Thanks for all the feedback and testing!!!
